# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-data
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: chatify
    role: cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      name: redis
      app: chatify
      role: cache
  template:
    metadata:
      labels:
        name: redis
        app: chatify
        role: cache
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
