apiVersion: v1
kind: Service
metadata:
  name: chatify-web
spec:
  selector:
    name: web
    app: chatify
  ports:
  - protocol: TCP
    name: default
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      app: chatify
  template:
    metadata:
      labels:
        name: web
        app: chatify
    spec:
      containers:
      - name: chatify-web
        image: vnikolaew/chatify.web:1.0.2
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_BACKEND_API_URL
          value: https://127.0.0.1:3001/api
        - name: COOKIE_CONSENT_ENABLED
          value: "1"
        ports:
        - containerPort: 3000
          name: default
