apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 90
  - protocol: TCP
    port: 443
    targetPort: 444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy
        ports:
        - containerPort: 90
        - containerPort: 444
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config
