apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels: {}
  name: "web-serber-lb"
spec:
  selector:
    app: chatify
    name: web-server
  type: LoadBalancer
  ports:
  - name: http
    port: 8083
    targetPort: 80
    nodePort: 32010
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app: chatify
    name: web-server
  ports:
  - protocol: TCP
    name: http
    port: 443
    targetPort: 443
  - protocol: TCP
    name: https
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatify
      name: web-server
  template:
    metadata:
      labels:
        name: web-server
        app: chatify
    spec:
      containers:
      - name: web-server
        image: vnikolaew/chatify.server:1.0.0
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_HTTP_PORT
          value: "80"
        - name: ASPNETCORE_HTTPS_PORT
          value: "443"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Redis__Endpoint
          value: "redis:6379"
        - name: Cassandra__ContactPoints__0
          value: "scylla"
        - name: Cassandra__Port
          value: "9042"
        - name: UseSeeding
          value: "false"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
