apiVersion: v1
kind: Service
metadata:
  name: chatify-web
spec:
  selector:
    name: web
    app: chatify
  ports:
  - protocol: TCP
    name: default
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatify-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      app: chatify
  template:
    metadata:
      labels:
        name: web
        app: chatify
    spec:
      containers:
      - name: chatify-web
        image:
        ports:
        - containerPort: 3000
          name: default
