version: '3.9'

services:
   caddy:
      image: caddy
      ports:
         - "90:80"
         - "444:443"
      volumes:
         - ./caddy/Caddyfile:/etc/caddy/Caddyfile
         - ./caddy/custom.pem:/etc/caddy/localhost-cert.pem
         - ./caddy/custom-key.pem:/etc/caddy/localhost-key.pem
      networks:
         default:
   chatify-web:
      build:
         context: .
         dockerfile: Dockerfile
      networks:
         default:
      ports:
         - "3000:3000"

networks:
   default:
volumes:
   caddy_data:
